project:
  type: book

book:
  title: "PhD-Thesis"
  author: "Michael Burtin"
  date: "01/10/2027"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - PBPK-Linezolid/article.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



